[MCS]
ApiKey = "MCS_xxxxx"       # Acquired from "https://www.multichain.storage" -> setting -> Create API Key
BucketName = "YOUR-BUCKET-NAME"                  # Acquired from "https://www.multichain.storage" -> bucket -> Add Bucket
Network = "polygon.mainnet"                   # polygon.mainnet for mainnet, polygon.mumbai for testnet

[HUB]
HUB_URL ="UBI-TASK-BASE-URL"
TASK_URL=""
CHECK_INTERVAL=1
BATCH_NUM=1
ENABLE_TITAN=1
TITAN_KEY=""
TITAN_FOLDER_512=607
TITAN_FOLDER_32=608

