[MCS]
ApiKey = "MCS_xxxxx"       # Acquired from "https://www.multichain.storage" -> setting -> Create API Key
BucketName = "YOUR-BUCKET-NAME"                  # Acquired from "https://www.multichain.storage" -> bucket -> Add Bucket
Network = "polygon.mainnet"                   # polygon.mainnet for mainnet, polygon.mumbai for testnet

HUB_URL ="UBI-TASK-BASE-URL"
